DROP DATABASE IF EXISTS videodb;
DROP USER IF EXISTS `videoadmin`@`%`;
DROP USER IF EXISTS `theuser`@`%`;
CREATE DATABASE IF NOT EXISTS videodb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `videoadmin`@`%` IDENTIFIED BY 'videoadmin';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `videodb`.* TO `videoadmin`@`%` WITH GRANT OPTION;
-- GRANT ALL ON `videodb`.* TO `videoadmin`@`%` WITH GRANT OPTION;
CREATE USER IF NOT EXISTS `theuser`@`%` IDENTIFIED BY 'theuser';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `videodb`.* TO `theuser`@`%`;
-- GRANT ALL ON `videodb`.* TO `theuser`@`%` WITH GRANT OPTION;
FLUSH PRIVILEGES;