spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE:dev}
  application:
    name: ${SPRING_APP_NAME:video-service}
  config:
    import:
      - optional:vault://secret/data/db/videodb/${SPRING_ACTIVE_PROFILE:dev}
      - optional:vault://secret/data/keycloak/${SPRING_ACTIVE_PROFILE:dev}
      - optional:configserver:http://cloud-config-service:9311
  devtools:
    restart:
      enabled: true
  threads:
    virtual:
      enabled: true
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  datasource:
    username: ${user:theuser}
    password: ${password:theuser}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/videodb}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_HIBERNATE_SHOW_SQL:false}
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:false}
  flyway:
    enabled: true
    user: ${flw-user:videoadmin}
    password: ${flw-password:videoadmin}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:${issuer-uri:http://localhost:8080/realms/company-platform}}
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN:srikanth}
      kv:
        enabled: true
        backend: secret
        profile-separator: /

server:
  port: ${SERVER_PORT:9161}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
  show-actuator: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka-discovery-service:9111/eureka}
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:info}
  pattern:
    level: ${LOG_PATTERN_CONSOLE:%green(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %blue(-%5level) %red([%thread]) %magenta(---){faint} %yellow(%logger{15}) - %msg%n}

info:
  app:
    name: ${spring.application.name}
