CREATE ROLE videoadmin LOGIN PASSWORD 'videoadmin';
CREATE ROLE theuser LOGIN PASSWORD 'theuser';
GRANT ALL ON SCHEMA public TO videoadmin;
GRANT CONNECT ON DATABASE videodb TO theuser;
GRANT USAGE ON SCHEMA public TO theuser;
ALTER DEFAULT PRIVILEGES FOR ROLE videoadmin IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO theuser;
